## Opening files

In [2]:
import pandas as pd

In [3]:
# queries

query_df = pd.read_xml("../data/kid-friend-en/en/inputs/topics.xml")
query_df.drop_duplicates(inplace=True, ignore_index=True)
query_df = query_df.rename({"number":"qid"}, axis=1)
query_df["query"] = ["".join([x if x.isalnum() else " " for x in query]) for query in query_df["query"]] # removing punctuations
query_df["qid"] = query_df["qid"].astype(str)
query_df.to_csv("../data/kid-friend-en/en/inputs/topics.csv", index=False)
query_df.head()

,qid,query,category,description,narrative
0,1,BTS,entertainment,Who are BTS? Where can I find their music?,Relevant documents for this request should inc...
1,2,BTS Bias Quiz,entertainment,Which band member suits me best? Which band me...,Relevant documents include kid-friendly conten...
2,3,BTS merch,entertainment,official BTS merch page and authorized sellers,Relevant documents redirect to fan articles of...
3,4,BTS Jungkook,entertainment,Who is Jungkook? What does he like? What does ...,Relevant documents contain information about J...
4,5,Minecraft,entertainment,What is Minecraft? Where can I play it? Let's ...,Relevant documents contain information about t...

In [18]:
# graded topical relevance

with open("../data/kid-friend-en/en/qrels/qrels-relevance.txt", "r") as f_qrel:
    lines= f_qrel.readlines()

qrels = []
for line in lines:
    qid, q0, docno, relevance = line.split(" ")
    qid = int(qid)
    relevance = int(relevance)
    qrels.append([qid, q0, docno, relevance])

qrels_df = pd.DataFrame(qrels, columns=["qid", "q0", "docno", "relevance"])
qrels_df["qid"] = qrels_df["qid"].astype(str)
print(len(qrels_df))
qrels_df.drop_duplicates(inplace=True, ignore_index=True)
print(len(qrels_df))

2303
2303

In [19]:
qrels_df = qrels_df.drop_duplicates(subset=["qid", "docno"], ignore_index=True, keep=False) # dropping qrels which have multiple relavances for a given (qid, docno) pair
len(qrels_df)

2303

In [20]:
qrels_df.to_csv("../data/kid-friend-en/en/qrels/qrels-relevance-graded.csv", index=False)
qrels_df.head()

  qid q0                             docno  relevance
0   1  0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1   1  0  c8a2aa042145402a8c180ca6f467c575          1
2   1  0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3   1  0  c8e3ba8d611441bebaf146001171af3a          1
4   1  0  44d7a109cd554b1cb44d2c3867ff7040          1

In [8]:
# binary topical relevance

qrels_df["relevance"] = [int(rel > 0) for rel in qrels_df["relevance"]]
qrels_df.to_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv", index=False)
qrels_df.head()

  qid q0                             docno  relevance
0   1  0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1   1  0  c8a2aa042145402a8c180ca6f467c575          1
2   1  0  d82e5e4f531841d49bcd6fe7bd8cdf8f          0
3   1  0  c8e3ba8d611441bebaf146001171af3a          1
4   1  0  44d7a109cd554b1cb44d2c3867ff7040          1

In [9]:
qrels_df.dtypes

qid          object
q0           object
docno        object
relevance     int64
dtype: object

In [10]:
query_df.dtypes

qid            object
query          object
category       object
description    object
narrative      object
dtype: object

## Adding more document features

### Readability

In [9]:
# adding readability (spache-allen) scores of documents

import json
import pandas as pd
from spache_allen.formula import spache_allen
from tqdm.notebook import tqdm

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
corpus["readability"] = [spache_allen(text) for text in tqdm(corpus["main_content"], total=len(corpus))]
corpus.to_csv("../data/kid-friend-en/en/inputs/documents.csv", index=False)
print(len(corpus))
corpus

  0%|          | 0/2385 [00:00<?, ?it/s]


  0%|          | 6/2385 [00:00<00:43, 54.48it/s]


  1%|          | 12/2385 [00:00<00:44, 53.03it/s]


  1%|          | 18/2385 [00:00<00:45, 52.35it/s]


  1%|          | 25/2385 [00:00<00:45, 51.56it/s]


  1%|▏         | 33/2385 [00:00<00:39, 59.14it/s]


  2%|▏         | 42/2385 [00:00<00:35, 65.17it/s]


  2%|▏         | 49/2385 [00:00<00:49, 47.33it/s]


  2%|▏         | 55/2385 [00:01<01:03, 36.62it/s]


  3%|▎         | 60/2385 [00:01<01:08, 33.70it/s]


  3%|▎         | 64/2385 [00:01<01:14, 31.15it/s]


  3%|▎         | 68/2385 [00:01<01:23, 27.87it/s]


  3%|▎         | 72/2385 [00:01<01:22, 27.92it/s]


  3%|▎         | 75/2385 [00:02<01:34, 24.53it/s]


  3%|▎         | 79/2385 [00:02<01:41, 22.72it/s]


  3%|▎         | 83/2385 [00:02<01:30, 25.46it/s]


  4%|▎         | 86/2385 [00:02<01:44, 21.91it/s]


  4%|▍         | 93/2385 [00:02<01:19, 28.95it/s]


  4%|▍         | 99/2385 [00:02<01:05, 35.12it/s]


  4%|▍         | 103/2385 [00:02<01:10, 32.22it/s]


  5%|▍         | 109/2385 [00:03<01:02, 36.65it/s]


  5%|▍         | 115/2385 [00:03<00:54, 42.01it/s]


  5%|▌         | 120/2385 [00:03<00:54, 41.89it/s]


  5%|▌         | 125/2385 [00:03<00:54, 41.18it/s]


  5%|▌         | 130/2385 [00:03<00:56, 39.76it/s]


  6%|▌         | 136/2385 [00:03<00:53, 42.32it/s]


  6%|▌         | 141/2385 [00:03<00:53, 41.80it/s]


  6%|▌         | 148/2385 [00:03<00:45, 48.86it/s]


  6%|▋         | 154/2385 [00:04<00:55, 40.50it/s]


  7%|▋         | 160/2385 [00:04<00:50, 43.71it/s]


  7%|▋         | 165/2385 [00:04<00:50, 43.65it/s]


  7%|▋         | 170/2385 [00:04<00:53, 41.40it/s]


  7%|▋         | 175/2385 [00:04<00:57, 38.64it/s]


  8%|▊         | 180/2385 [00:04<01:02, 35.15it/s]


  8%|▊         | 186/2385 [00:04<00:55, 39.98it/s]


  8%|▊         | 191/2385 [00:05<00:56, 38.97it/s]


  8%|▊         | 196/2385 [00:05<00:59, 36.87it/s]


  8%|▊         | 200/2385 [00:05<00:59, 36.98it/s]


  9%|▊         | 207/2385 [00:05<00:50, 43.37it/s]


  9%|▉         | 213/2385 [00:05<00:47, 46.12it/s]


  9%|▉         | 220/2385 [00:05<00:43, 50.05it/s]


  9%|▉         | 226/2385 [00:05<00:41, 52.01it/s]


 10%|▉         | 232/2385 [00:05<00:42, 50.96it/s]


 10%|▉         | 238/2385 [00:06<00:47, 45.21it/s]


 10%|█         | 243/2385 [00:06<00:58, 36.49it/s]


 10%|█         | 248/2385 [00:06<00:54, 39.26it/s]


 11%|█         | 253/2385 [00:06<00:57, 37.40it/s]


 11%|█         | 258/2385 [00:06<00:52, 40.17it/s]


 11%|█         | 263/2385 [00:06<01:20, 26.29it/s]


 11%|█         | 267/2385 [00:07<01:29, 23.54it/s]


 11%|█▏        | 271/2385 [00:07<01:22, 25.57it/s]


 12%|█▏        | 275/2385 [00:07<01:18, 26.97it/s]


 12%|█▏        | 279/2385 [00:07<01:18, 26.86it/s]


 12%|█▏        | 283/2385 [00:07<01:11, 29.55it/s]


 12%|█▏        | 287/2385 [00:07<01:25, 24.42it/s]


 12%|█▏        | 290/2385 [00:08<01:22, 25.45it/s]


 12%|█▏        | 293/2385 [00:08<01:53, 18.39it/s]


 12%|█▏        | 296/2385 [00:08<01:43, 20.22it/s]


 13%|█▎        | 299/2385 [00:08<02:05, 16.64it/s]


 13%|█▎        | 304/2385 [00:08<01:37, 21.35it/s]


 13%|█▎        | 308/2385 [00:08<01:23, 24.75it/s]


 13%|█▎        | 311/2385 [00:09<01:34, 21.95it/s]


 13%|█▎        | 315/2385 [00:09<01:21, 25.29it/s]


 13%|█▎        | 320/2385 [00:09<01:08, 30.01it/s]


 14%|█▎        | 324/2385 [00:09<01:23, 24.66it/s]


 14%|█▍        | 328/2385 [00:09<01:14, 27.43it/s]


 14%|█▍        | 332/2385 [00:09<01:14, 27.57it/s]


 14%|█▍        | 336/2385 [00:09<01:09, 29.66it/s]


 14%|█▍        | 340/2385 [00:10<01:41, 20.14it/s]


 14%|█▍        | 344/2385 [00:10<01:27, 23.44it/s]


 15%|█▍        | 347/2385 [00:10<01:43, 19.78it/s]


 15%|█▍        | 350/2385 [00:10<01:51, 18.18it/s]


 15%|█▍        | 354/2385 [00:11<02:05, 16.20it/s]


 15%|█▍        | 357/2385 [00:11<01:51, 18.16it/s]


 15%|█▌        | 360/2385 [00:11<01:50, 18.26it/s]


 15%|█▌        | 366/2385 [00:11<01:20, 25.07it/s]


 15%|█▌        | 369/2385 [00:11<01:19, 25.27it/s]


 16%|█▌        | 373/2385 [00:11<01:20, 24.97it/s]


 16%|█▌        | 377/2385 [00:11<01:18, 25.47it/s]


 16%|█▌        | 380/2385 [00:12<01:17, 25.90it/s]


 16%|█▌        | 383/2385 [00:12<01:39, 20.10it/s]


 16%|█▋        | 388/2385 [00:12<01:18, 25.56it/s]


 16%|█▋        | 392/2385 [00:12<01:20, 24.82it/s]


 17%|█▋        | 398/2385 [00:12<01:03, 31.17it/s]


 17%|█▋        | 402/2385 [00:12<01:03, 31.30it/s]


 17%|█▋        | 406/2385 [00:13<01:10, 27.95it/s]


 17%|█▋        | 410/2385 [00:13<01:11, 27.56it/s]


 17%|█▋        | 416/2385 [00:13<01:01, 31.96it/s]


 18%|█▊        | 422/2385 [00:13<00:52, 37.37it/s]


 18%|█▊        | 427/2385 [00:13<00:48, 40.28it/s]


 18%|█▊        | 432/2385 [00:13<00:47, 41.43it/s]


 18%|█▊        | 438/2385 [00:13<00:44, 43.63it/s]


 19%|█▊        | 443/2385 [00:13<00:44, 43.91it/s]


 19%|█▉        | 448/2385 [00:14<00:48, 39.99it/s]


 19%|█▉        | 454/2385 [00:14<00:43, 44.01it/s]


 19%|█▉        | 459/2385 [00:14<00:45, 42.57it/s]


 19%|█▉        | 464/2385 [00:14<00:45, 42.55it/s]


 20%|█▉        | 469/2385 [00:14<00:51, 37.10it/s]


 20%|█▉        | 473/2385 [00:14<00:58, 32.44it/s]


 20%|██        | 477/2385 [00:14<01:10, 27.22it/s]


 20%|██        | 480/2385 [00:15<01:11, 26.81it/s]


 20%|██        | 483/2385 [00:15<01:20, 23.67it/s]


 20%|██        | 487/2385 [00:15<01:17, 24.45it/s]


 21%|██        | 492/2385 [00:15<01:05, 29.05it/s]


 21%|██        | 496/2385 [00:15<01:05, 28.67it/s]


 21%|██        | 499/2385 [00:15<01:07, 27.88it/s]


 21%|██        | 502/2385 [00:15<01:08, 27.62it/s]


 21%|██        | 506/2385 [00:16<01:06, 28.14it/s]


 21%|██▏       | 511/2385 [00:16<01:03, 29.53it/s]


 22%|██▏       | 514/2385 [00:16<01:10, 26.49it/s]


 22%|██▏       | 517/2385 [00:16<01:13, 25.31it/s]


 22%|██▏       | 524/2385 [00:16<00:52, 35.68it/s]


 22%|██▏       | 528/2385 [00:16<01:15, 24.48it/s]


 22%|██▏       | 535/2385 [00:17<01:03, 29.32it/s]


 23%|██▎       | 543/2385 [00:17<00:48, 37.82it/s]


 23%|██▎       | 550/2385 [00:17<00:41, 43.80it/s]


 23%|██▎       | 558/2385 [00:17<00:35, 51.24it/s]


 24%|██▎       | 566/2385 [00:17<00:33, 54.01it/s]


 24%|██▍       | 573/2385 [00:17<00:31, 56.71it/s]


 24%|██▍       | 580/2385 [00:17<00:32, 56.11it/s]


 25%|██▍       | 587/2385 [00:17<00:31, 56.94it/s]


 25%|██▍       | 594/2385 [00:17<00:30, 59.17it/s]


 25%|██▌       | 601/2385 [00:18<00:29, 60.29it/s]


 25%|██▌       | 608/2385 [00:18<00:29, 60.83it/s]


 26%|██▌       | 615/2385 [00:18<00:30, 58.47it/s]


 26%|██▌       | 621/2385 [00:18<00:32, 55.02it/s]


 26%|██▋       | 628/2385 [00:18<00:30, 57.55it/s]


 27%|██▋       | 634/2385 [00:18<00:33, 53.03it/s]


 27%|██▋       | 640/2385 [00:18<00:35, 49.20it/s]


 27%|██▋       | 646/2385 [00:18<00:38, 44.72it/s]


 27%|██▋       | 653/2385 [00:19<00:36, 47.67it/s]


 28%|██▊       | 658/2385 [00:19<00:40, 42.35it/s]


 28%|██▊       | 663/2385 [00:19<00:44, 38.37it/s]


 28%|██▊       | 667/2385 [00:19<00:46, 37.13it/s]


 28%|██▊       | 671/2385 [00:19<00:50, 33.89it/s]


 28%|██▊       | 676/2385 [00:19<00:46, 36.38it/s]


 29%|██▊       | 680/2385 [00:20<00:55, 30.66it/s]


 29%|██▊       | 684/2385 [00:20<01:03, 26.90it/s]


 29%|██▉       | 687/2385 [00:20<01:19, 21.39it/s]


 29%|██▉       | 690/2385 [00:20<01:18, 21.62it/s]


 29%|██▉       | 693/2385 [00:20<01:25, 19.85it/s]


 29%|██▉       | 697/2385 [00:20<01:24, 19.88it/s]


 29%|██▉       | 700/2385 [00:21<01:39, 16.93it/s]


 30%|██▉       | 705/2385 [00:21<01:14, 22.53it/s]


 30%|██▉       | 709/2385 [00:21<01:05, 25.58it/s]


 30%|██▉       | 713/2385 [00:21<01:02, 26.75it/s]


 30%|███       | 719/2385 [00:21<00:50, 33.12it/s]


 30%|███       | 723/2385 [00:21<00:48, 34.47it/s]


 30%|███       | 727/2385 [00:21<00:50, 32.83it/s]


 31%|███       | 733/2385 [00:22<00:42, 38.85it/s]


 31%|███       | 740/2385 [00:22<00:35, 46.21it/s]


 31%|███▏      | 747/2385 [00:22<00:36, 44.95it/s]


 32%|███▏      | 752/2385 [00:22<00:38, 42.15it/s]


 32%|███▏      | 759/2385 [00:22<00:33, 48.85it/s]


 32%|███▏      | 765/2385 [00:22<00:59, 27.02it/s]


 32%|███▏      | 770/2385 [00:23<01:00, 26.72it/s]


 32%|███▏      | 775/2385 [00:23<00:53, 30.15it/s]


 33%|███▎      | 780/2385 [00:23<00:50, 32.06it/s]


 33%|███▎      | 784/2385 [00:23<01:09, 22.97it/s]


 33%|███▎      | 791/2385 [00:23<01:01, 26.08it/s]


 33%|███▎      | 795/2385 [00:24<00:56, 28.12it/s]


 34%|███▎      | 799/2385 [00:24<00:53, 29.91it/s]


 34%|███▎      | 803/2385 [00:24<00:49, 31.86it/s]


 34%|███▍      | 807/2385 [00:24<00:47, 33.04it/s]


 34%|███▍      | 812/2385 [00:24<00:47, 32.90it/s]


 34%|███▍      | 817/2385 [00:24<00:44, 35.07it/s]


 34%|███▍      | 821/2385 [00:24<00:56, 27.85it/s]


 35%|███▍      | 827/2385 [00:25<00:47, 32.58it/s]


 35%|███▍      | 834/2385 [00:25<00:40, 38.12it/s]


 35%|███▌      | 839/2385 [00:25<00:51, 30.10it/s]


 35%|███▌      | 846/2385 [00:25<00:45, 33.94it/s]


 36%|███▌      | 850/2385 [00:25<00:44, 34.39it/s]


 36%|███▌      | 856/2385 [00:25<00:39, 39.17it/s]


 36%|███▌      | 861/2385 [00:25<00:37, 41.02it/s]


 36%|███▋      | 866/2385 [00:26<00:42, 36.09it/s]


 37%|███▋      | 874/2385 [00:26<00:33, 44.89it/s]


 37%|███▋      | 879/2385 [00:26<00:33, 45.52it/s]


 37%|███▋      | 886/2385 [00:26<00:29, 51.47it/s]


 37%|███▋      | 892/2385 [00:26<00:29, 50.41it/s]


 38%|███▊      | 898/2385 [00:26<00:32, 46.01it/s]


 38%|███▊      | 903/2385 [00:26<00:32, 46.29it/s]


 38%|███▊      | 908/2385 [00:26<00:31, 47.02it/s]


 38%|███▊      | 914/2385 [00:26<00:29, 50.27it/s]


 39%|███▊      | 920/2385 [00:27<00:47, 30.76it/s]


 39%|███▉      | 927/2385 [00:27<00:38, 37.87it/s]


 39%|███▉      | 935/2385 [00:27<00:31, 45.67it/s]


 39%|███▉      | 941/2385 [00:27<00:31, 45.66it/s]


 40%|███▉      | 947/2385 [00:27<00:33, 43.10it/s]


 40%|███▉      | 952/2385 [00:27<00:33, 42.79it/s]


 40%|████      | 958/2385 [00:28<00:30, 46.20it/s]


 40%|████      | 965/2385 [00:28<00:27, 51.47it/s]


 41%|████      | 971/2385 [00:28<00:32, 43.66it/s]


 41%|████      | 976/2385 [00:28<00:33, 41.94it/s]


 41%|████      | 981/2385 [00:28<00:38, 36.80it/s]


 41%|████▏     | 985/2385 [00:28<00:47, 29.20it/s]


 41%|████▏     | 989/2385 [00:29<01:04, 21.80it/s]


 42%|████▏     | 992/2385 [00:29<01:01, 22.63it/s]


 42%|████▏     | 997/2385 [00:29<00:52, 26.69it/s]


 42%|████▏     | 1003/2385 [00:29<00:43, 31.83it/s]


 42%|████▏     | 1008/2385 [00:29<00:39, 34.98it/s]


 42%|████▏     | 1013/2385 [00:29<00:42, 32.03it/s]


 43%|████▎     | 1017/2385 [00:29<00:41, 32.93it/s]


 43%|████▎     | 1022/2385 [00:30<00:37, 36.55it/s]


 43%|████▎     | 1026/2385 [00:30<00:42, 32.04it/s]


 43%|████▎     | 1030/2385 [00:30<00:45, 29.89it/s]


 43%|████▎     | 1034/2385 [00:30<00:43, 30.76it/s]


 44%|████▎     | 1038/2385 [00:30<00:43, 31.15it/s]


 44%|████▎     | 1042/2385 [00:30<00:47, 28.07it/s]


 44%|████▍     | 1047/2385 [00:30<00:40, 32.80it/s]


 44%|████▍     | 1051/2385 [00:31<00:41, 32.01it/s]


 44%|████▍     | 1055/2385 [00:31<00:42, 31.53it/s]


 44%|████▍     | 1059/2385 [00:31<00:41, 31.95it/s]


 45%|████▍     | 1064/2385 [00:31<00:45, 29.34it/s]


 45%|████▍     | 1068/2385 [00:31<00:43, 30.17it/s]


 45%|████▍     | 1073/2385 [00:31<00:40, 32.60it/s]


 45%|████▌     | 1077/2385 [00:32<01:00, 21.59it/s]


 45%|████▌     | 1082/2385 [00:32<00:49, 26.30it/s]


 46%|████▌     | 1087/2385 [00:32<00:42, 30.40it/s]


 46%|████▌     | 1092/2385 [00:32<00:37, 34.06it/s]


 46%|████▌     | 1096/2385 [00:32<00:40, 31.82it/s]


 46%|████▌     | 1100/2385 [00:32<00:44, 28.87it/s]


 46%|████▋     | 1105/2385 [00:32<00:38, 33.01it/s]


 47%|████▋     | 1111/2385 [00:33<00:33, 38.22it/s]


 47%|████▋     | 1116/2385 [00:33<00:31, 40.18it/s]


 47%|████▋     | 1122/2385 [00:33<00:35, 35.29it/s]


 47%|████▋     | 1126/2385 [00:33<00:35, 35.59it/s]


 47%|████▋     | 1130/2385 [00:33<00:35, 35.62it/s]


 48%|████▊     | 1135/2385 [00:33<00:32, 38.89it/s]


 48%|████▊     | 1141/2385 [00:33<00:28, 43.83it/s]


 48%|████▊     | 1147/2385 [00:33<00:27, 44.88it/s]


 48%|████▊     | 1154/2385 [00:33<00:24, 49.92it/s]


 49%|████▊     | 1160/2385 [00:34<00:24, 50.41it/s]


 49%|████▉     | 1166/2385 [00:34<00:27, 43.88it/s]


 49%|████▉     | 1171/2385 [00:34<00:30, 40.34it/s]


 49%|████▉     | 1178/2385 [00:34<00:26, 45.48it/s]


 50%|████▉     | 1185/2385 [00:34<00:26, 45.40it/s]


 50%|████▉     | 1190/2385 [00:34<00:33, 35.34it/s]


 50%|█████     | 1195/2385 [00:35<00:34, 34.93it/s]


 50%|█████     | 1200/2385 [00:35<00:31, 37.51it/s]


 51%|█████     | 1205/2385 [00:35<00:31, 37.12it/s]


 51%|█████     | 1210/2385 [00:35<00:31, 37.19it/s]


 51%|█████     | 1215/2385 [00:35<00:29, 39.40it/s]


 51%|█████     | 1220/2385 [00:35<00:28, 40.28it/s]


 51%|█████▏    | 1225/2385 [00:35<00:28, 40.32it/s]


 52%|█████▏    | 1230/2385 [00:35<00:30, 37.51it/s]


 52%|█████▏    | 1234/2385 [00:36<00:33, 34.56it/s]


 52%|█████▏    | 1238/2385 [00:36<00:43, 26.24it/s]


 52%|█████▏    | 1243/2385 [00:36<00:37, 30.86it/s]


 52%|█████▏    | 1249/2385 [00:36<00:31, 36.03it/s]


 53%|█████▎    | 1254/2385 [00:36<00:39, 28.79it/s]


 53%|█████▎    | 1258/2385 [00:36<00:37, 30.22it/s]


 53%|█████▎    | 1262/2385 [00:37<00:53, 21.04it/s]


 53%|█████▎    | 1266/2385 [00:37<00:46, 24.17it/s]


 53%|█████▎    | 1271/2385 [00:37<00:38, 28.68it/s]


 54%|█████▎    | 1276/2385 [00:37<00:36, 30.70it/s]


 54%|█████▎    | 1280/2385 [00:37<00:35, 31.25it/s]


 54%|█████▍    | 1285/2385 [00:37<00:30, 35.53it/s]


 54%|█████▍    | 1289/2385 [00:38<00:31, 34.31it/s]


 54%|█████▍    | 1293/2385 [00:38<00:37, 28.86it/s]


 54%|█████▍    | 1297/2385 [00:38<00:38, 28.41it/s]


 55%|█████▍    | 1303/2385 [00:38<00:32, 33.78it/s]


 55%|█████▍    | 1308/2385 [00:38<00:29, 36.56it/s]


 55%|█████▌    | 1312/2385 [00:38<00:31, 34.31it/s]


 55%|█████▌    | 1317/2385 [00:38<00:28, 37.30it/s]


 55%|█████▌    | 1321/2385 [00:38<00:29, 35.93it/s]


 56%|█████▌    | 1325/2385 [00:39<00:31, 33.53it/s]


 56%|█████▌    | 1329/2385 [00:39<00:30, 34.60it/s]


 56%|█████▌    | 1333/2385 [00:39<00:29, 35.43it/s]


 56%|█████▌    | 1338/2385 [00:39<00:31, 33.65it/s]


 56%|█████▋    | 1342/2385 [00:39<00:29, 34.98it/s]


 56%|█████▋    | 1346/2385 [00:39<00:41, 25.09it/s]


 57%|█████▋    | 1349/2385 [00:39<00:40, 25.67it/s]


 57%|█████▋    | 1354/2385 [00:40<00:33, 30.35it/s]


 57%|█████▋    | 1360/2385 [00:40<00:28, 36.19it/s]


 57%|█████▋    | 1364/2385 [00:40<00:28, 35.65it/s]


 57%|█████▋    | 1369/2385 [00:40<00:26, 38.10it/s]


 58%|█████▊    | 1377/2385 [00:40<00:23, 42.41it/s]


 58%|█████▊    | 1384/2385 [00:40<00:21, 46.50it/s]


 58%|█████▊    | 1391/2385 [00:40<00:19, 52.22it/s]


 59%|█████▊    | 1397/2385 [00:40<00:18, 52.88it/s]


 59%|█████▉    | 1403/2385 [00:41<00:18, 51.73it/s]


 59%|█████▉    | 1411/2385 [00:41<00:16, 57.88it/s]


 59%|█████▉    | 1417/2385 [00:41<00:16, 58.18it/s]


 60%|█████▉    | 1424/2385 [00:41<00:15, 60.65it/s]


 60%|██████    | 1431/2385 [00:41<00:16, 58.23it/s]


 60%|██████    | 1437/2385 [00:41<00:20, 46.77it/s]


 61%|██████    | 1443/2385 [00:41<00:19, 49.53it/s]


 61%|██████    | 1450/2385 [00:41<00:17, 53.61it/s]


 61%|██████    | 1457/2385 [00:41<00:16, 55.08it/s]


 61%|██████▏   | 1463/2385 [00:42<00:16, 54.43it/s]


 62%|██████▏   | 1469/2385 [00:42<00:16, 55.05it/s]


 62%|██████▏   | 1476/2385 [00:42<00:15, 57.61it/s]


 62%|██████▏   | 1482/2385 [00:42<00:16, 55.28it/s]


 62%|██████▏   | 1488/2385 [00:42<00:17, 50.32it/s]


 63%|██████▎   | 1494/2385 [00:42<00:18, 49.02it/s]


 63%|██████▎   | 1501/2385 [00:42<00:16, 52.49it/s]


 63%|██████▎   | 1508/2385 [00:42<00:15, 56.43it/s]


 63%|██████▎   | 1514/2385 [00:43<00:15, 55.96it/s]


 64%|██████▎   | 1520/2385 [00:43<00:26, 32.94it/s]


 64%|██████▍   | 1525/2385 [00:43<00:26, 32.31it/s]


 64%|██████▍   | 1530/2385 [00:43<00:32, 26.07it/s]


 64%|██████▍   | 1534/2385 [00:44<00:41, 20.62it/s]


 65%|██████▍   | 1539/2385 [00:44<00:34, 24.26it/s]


 65%|██████▍   | 1544/2385 [00:44<00:33, 25.12it/s]


 65%|██████▍   | 1550/2385 [00:44<00:27, 30.36it/s]


 65%|██████▌   | 1554/2385 [00:44<00:35, 23.49it/s]


 65%|██████▌   | 1558/2385 [00:45<00:31, 26.22it/s]


 66%|██████▌   | 1563/2385 [00:45<00:28, 28.81it/s]


 66%|██████▌   | 1569/2385 [00:45<00:23, 34.91it/s]


 66%|██████▌   | 1575/2385 [00:45<00:20, 39.74it/s]


 66%|██████▌   | 1580/2385 [00:45<00:19, 41.41it/s]


 67%|██████▋   | 1587/2385 [00:45<00:16, 46.96it/s]


 67%|██████▋   | 1593/2385 [00:45<00:16, 49.26it/s]


 67%|██████▋   | 1601/2385 [00:45<00:17, 44.37it/s]


 67%|██████▋   | 1606/2385 [00:46<00:17, 43.47it/s]


 68%|██████▊   | 1611/2385 [00:46<00:17, 43.56it/s]


 68%|██████▊   | 1616/2385 [00:46<00:21, 36.38it/s]


 68%|██████▊   | 1621/2385 [00:46<00:20, 37.93it/s]


 68%|██████▊   | 1627/2385 [00:46<00:17, 42.33it/s]


 69%|██████▊   | 1634/2385 [00:46<00:15, 49.10it/s]


 69%|██████▉   | 1640/2385 [00:46<00:14, 51.92it/s]


 69%|██████▉   | 1646/2385 [00:47<00:27, 26.59it/s]


 69%|██████▉   | 1651/2385 [00:47<00:24, 30.05it/s]


 69%|██████▉   | 1656/2385 [00:47<00:23, 31.19it/s]


 70%|██████▉   | 1661/2385 [00:47<00:29, 24.63it/s]


 70%|██████▉   | 1668/2385 [00:47<00:22, 31.39it/s]


 70%|███████   | 1673/2385 [00:48<00:35, 20.01it/s]


 70%|███████   | 1677/2385 [00:48<00:33, 21.38it/s]


 70%|███████   | 1681/2385 [00:48<00:32, 21.62it/s]


 71%|███████   | 1687/2385 [00:48<00:25, 27.39it/s]


 71%|███████   | 1692/2385 [00:48<00:22, 30.71it/s]


 71%|███████   | 1696/2385 [00:49<00:44, 15.58it/s]


 71%|███████▏  | 1701/2385 [00:49<00:34, 19.68it/s]


 72%|███████▏  | 1708/2385 [00:49<00:25, 26.98it/s]


 72%|███████▏  | 1713/2385 [00:50<00:25, 25.94it/s]


 72%|███████▏  | 1717/2385 [00:50<00:23, 28.08it/s]


 72%|███████▏  | 1724/2385 [00:50<00:20, 32.52it/s]


 73%|███████▎  | 1730/2385 [00:50<00:25, 25.56it/s]


 73%|███████▎  | 1735/2385 [00:50<00:22, 29.05it/s]


 73%|███████▎  | 1742/2385 [00:50<00:18, 34.78it/s]


 73%|███████▎  | 1748/2385 [00:50<00:16, 39.26it/s]


 74%|███████▎  | 1753/2385 [00:51<00:16, 38.63it/s]


 74%|███████▍  | 1759/2385 [00:51<00:14, 42.46it/s]


 74%|███████▍  | 1764/2385 [00:51<00:14, 44.19it/s]


 74%|███████▍  | 1770/2385 [00:51<00:13, 47.09it/s]


 74%|███████▍  | 1775/2385 [00:51<00:17, 35.40it/s]


 75%|███████▍  | 1781/2385 [00:51<00:15, 40.11it/s]


 75%|███████▍  | 1786/2385 [00:51<00:17, 35.20it/s]


 75%|███████▌  | 1791/2385 [00:52<00:16, 36.82it/s]


 75%|███████▌  | 1796/2385 [00:52<00:15, 39.04it/s]


 76%|███████▌  | 1801/2385 [00:52<00:18, 32.26it/s]


 76%|███████▌  | 1805/2385 [00:52<00:17, 33.40it/s]


 76%|███████▌  | 1812/2385 [00:52<00:14, 40.90it/s]


 76%|███████▌  | 1817/2385 [00:52<00:15, 36.49it/s]


 76%|███████▋  | 1822/2385 [00:52<00:14, 38.63it/s]


 77%|███████▋  | 1827/2385 [00:53<00:17, 32.77it/s]


 77%|███████▋  | 1833/2385 [00:53<00:15, 34.68it/s]


 77%|███████▋  | 1837/2385 [00:53<00:15, 34.53it/s]


 77%|███████▋  | 1841/2385 [00:53<00:15, 34.78it/s]


 77%|███████▋  | 1847/2385 [00:53<00:13, 40.21it/s]


 78%|███████▊  | 1852/2385 [00:53<00:12, 41.07it/s]


 78%|███████▊  | 1857/2385 [00:53<00:15, 33.25it/s]


 78%|███████▊  | 1863/2385 [00:54<00:13, 39.05it/s]


 78%|███████▊  | 1870/2385 [00:54<00:11, 43.83it/s]


 79%|███████▊  | 1875/2385 [00:54<00:22, 22.34it/s]


 79%|███████▉  | 1881/2385 [00:54<00:18, 27.55it/s]


 79%|███████▉  | 1887/2385 [00:54<00:15, 32.32it/s]


 79%|███████▉  | 1892/2385 [00:55<00:16, 30.12it/s]


 80%|███████▉  | 1898/2385 [00:55<00:13, 35.46it/s]


 80%|███████▉  | 1904/2385 [00:55<00:12, 37.94it/s]


 80%|████████  | 1909/2385 [00:55<00:11, 39.90it/s]


 80%|████████  | 1915/2385 [00:55<00:10, 43.29it/s]


 81%|████████  | 1920/2385 [00:55<00:11, 42.06it/s]


 81%|████████  | 1925/2385 [00:55<00:13, 34.91it/s]



2385

,docno,snippet,title,main_content,readability
0,6e421f1539b1457b853712d81be87743,WEBBTS (also Bangtan Boys; Korean: 방탄소년단 Bangt...,BTS (band) - Wikipedia,BTS (also Bangtan Boys; Korean: 방탄소년단 Bangtan ...,6.714078
1,1539268e3f1d41c9abcaa277b23f51d9,WEBMusic video by BTS performing Dynamite. (C)...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,7.757287
2,93689ea1c0ec4272b41d7b259cb47890,Biography BTS is a Grammy-nominated South Kore...,Before you go on to YouTube,YouTube\nA Google company\n\nBefore you go on ...,7.757287
3,2e4321c5105840c8b6612f87dc4aba13,WEBBTS (Korean: 방탄소년단; RR: Bangtan Sonyeondan;...,BTS - Wikipedia,BTS (Korean방탄소년단; RRBangtan Sonyeondan; lit. B...,8.258022
4,3d21474fff4e406c9db2984d5edf647b,"WEBTo avoid this, cancel and sign in to YouTub...",BTS (방탄소년단) 'Yet To Come (The Most Beautiful M...,"So, Who is missing BTS badly. Let's stay stron...",6.958174
...,...,...,...,...,...
2380,648909aa33704dee80d34cda654ed0e3,"Sep 27, 2021 -\nWho likes school???????\n...\n...",Who likes school??????? | Page strong,Who likes school???????\n\nWho likes school???...,5.494769
2381,caa7c7203c2049f9a5257439f5e7b822,"Mar 8, 2021 -\nWho knows or likes the music of...",Who knows or likes the music of Sarah Lombardi...,Who knows or likes the music of Sarah Lombardi...,6.481945
2382,3cf211d4b8fd4884bfbb4b3c46305c8b,"Mar 8, 2021 -\nWho knows or likes DSDS?\n... t...",Who knows or likes DSDS??? | Page strong,Who knows or likes DSDS???\n\nWho knows or lik...,4.946886
2383,bf691cd32f2f47a98b8f6673dd47ea18,"Apr 1, 2022 - ... wand, Severus walked slowly...",Severus Snape meets his daughter ( Chapter 1 T...,Severus Snape meets his daughter ( Chapter 1 H...,4.063169
2384,748731d015c649e589f9fee65262bce4,"Oct 16, 2023 - ...\nHow do I tell my girlfrien...",How do I tell my girlfriend to call me Noah? |...,How do I tell my girlfriend to call me Noah?\n...,4.555605

In [12]:
import pandas as pd

df = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
len(df)

2385

In [13]:
import pandas as pd
import json

lines = []
with open(r'../data/kid-friend-en/en/inputs/documents.jsonl') as f:
    lines = f.read().splitlines()

line_dicts = [json.loads(line) for line in lines]
corpus = pd.DataFrame(line_dicts)
corpus.drop_duplicates(inplace=True,ignore_index=True)
len(corpus.loc[corpus["main_content"]==""]), len(corpus.loc[(corpus["main_content"]=="")&(corpus["snippet"]=="")]), len(corpus.loc[(corpus["main_content"]=="")&(corpus["snippet"]=="")&(corpus["title"]=="")])

(187, 15, 7)

In [14]:
corpus_df = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
corpus_df.loc[(corpus_df["readability"]<0)&(corpus_df["main_content"].isna()==False)]

,docno,snippet,title,main_content,readability
1815,6631c7692a2148beae63c0bdb6c82e70,NaN,Like a leaping dolphin,icon-angle icon-bars icon-times,-1.0

In [15]:
corpus_df.loc[(corpus_df["readability"]<0)]

,docno,snippet,title,main_content,readability
5,37d53c33110a4231807e71e377f08377,"Discover BTS, the global superstars of K-pop, ...",BTS | BIGHIT MUSIC,NaN,-1.0
6,aa31a4d64bbf4accb37f37762307634f,The official website for BTS,BTS | BIGHIT MUSIC,NaN,-1.0
30,8180b99992b34e2ab0813e50222884ba,Minecraft is a sandbox game where you can crea...,NaN,NaN,-1.0
34,3888836f228d4701913acdd11c688f86,"WEBBuild with sculk, mud, and mangrove wood. T...",The Wild Update: Craft Your Path - Official Mi...,NaN,-1.0
38,c8d52a8560894eb4affaa083af21edbb,WEB4 days ago - Minecraft Java 1.21.1 Released...,NaN,NaN,-1.0
...,...,...,...,...,...
2256,3e606883584d44e29dc248a25e71fe86,"Profession: vet - Sure, everyone wants to hel...",NaN,NaN,-1.0
2308,162c880249254e06b976f5b4d63c9601,"May 13, 2024 - ...\nWhat are the reasons for a...",War in Ukraine | Seitenstark,NaN,-1.0
2311,06180d11fdb844f28157d0814476ca2c,"Dec 10, 2018 -\nIn this article, children lear...",Climate change | Seitenstark,NaN,-1.0
2312,c573e2778ac74ecd8d9be00790235fba,"Nov 21, 2018 -\nTemperatures on our planet are...",Climate change and climate protection | Seiten...,NaN,-1.0
2314,dccf8df6998c400b8a706469586787b8,"Oct 31, 2022 -\nClimate change affects us all ...",Interactive whiteboard: Climate change | Seite...,NaN,-1.0

### Objectivity

### Educational Alignment

## Creating other versions of ground truth

In [16]:
# # binary readability relevance: all docs paired with each qid

# query_df = pd.read_csv("../kid-friend-en/en/inputs/topics.csv")
# corpus = pd.read_csv("../kid-friend-en/en/inputs/documents.csv")
# qids = query_df["qid"].unique()

# read_qrels = []
# for qid in qids:
#     for _, row in corpus.iterrows():
#         if row["readability"] < 0: # removing query-doc pairs where the readability score is invalid (i.e., the score < 0)
#             continue
#         read_qrels.append([qid, "q0", row["docno"], int(int(row["readability"]) <= 4)])

# readability_qrels = pd.DataFrame(read_qrels, columns=["qid", "q0", "docno", "relevance"])
# readability_qrels.to_csv("../kid-friend-en/en/qrels/qrels-readability-alldocs.csv", index=False)
# readability_qrels.head()

In [17]:
# assert len(query_df)*len(corpus.loc[corpus["readability"]>0]) == len(readability_qrels)

### Relevance + Readability

In [22]:
# binary readability relevance: same query-doc pairs as qrels-relevance-binary.txt 
# query-doc pair assigned 1 if relevant and readable; 0 otherwise

from tqdm import tqdm
import pandas as pd

# nltk.download('all', halt_on_error=False)
corpus = pd.read_csv("../data/kid-friend-en/en/inputs/documents.csv")
qrels_df = pd.read_csv("../data/kid-friend-en/en/qrels/qrels-relevance-binary.csv")
read_relevance = []
issue_docs = []

for _, row in tqdm(qrels_df.iterrows(), total=len(qrels_df)):
    qid = row["qid"]
    docid = row["docno"]
    relevance = row["relevance"]
    readability = list(corpus.loc[corpus["docno"]==docid]["readability"])[0]
    if readability < 0: # removing query-doc pairs where the readability score is invalid (i.e., the score < 0)
        issue_docs.append(docid)
        continue
    else:
        read_relevance.append([qid, "q0", docid, relevance*int(int(readability)<=4)])

qrels_readability_df = pd.DataFrame(read_relevance, columns=["qid", "q0", "docno", "relevance"])
qrels_readability_df.to_csv("../data/kid-friend-en/en/qrels/qrels-readability-binary.csv", index=False)
qrels_readability_df

  0%|          | 0/2303 [00:00<?, ?it/s]





 13%|█▎        | 289/2303 [00:00<00:00, 2883.96it/s]





 26%|██▌       | 593/2303 [00:00<00:00, 2974.66it/s]





 39%|███▉      | 902/2303 [00:00<00:00, 3025.88it/s]





 53%|█████▎    | 1210/2303 [00:00<00:00, 3044.29it/s]





 67%|██████▋   | 1532/2303 [00:00<00:00, 3104.99it/s]





 80%|████████  | 1843/2303 [00:00<00:00, 3073.86it/s]





100%|██████████| 2303/2303 [00:00<00:00, 3051.03it/s]

      qid  q0                             docno  relevance
0       1  q0  77cdd0f6c3b04b5bbe79fac37c2ae63b          0
1       1  q0  c8a2aa042145402a8c180ca6f467c575          0
2       1  q0  c8e3ba8d611441bebaf146001171af3a          0
3       1  q0  58e44787b87844e4a968d6eb1edf94bd          0
4       1  q0  f2ef0e00fdcf42cfa9e4d364c0282379          1
...   ...  ..                               ...        ...
2133   50  q0  b7646dcb4b134afbacbe9a61a4ef914e          0
2134   50  q0  bc5f268885cb41379f06ced62f96adbb          0
2135   50  q0  c5840e5e858d4baa97ecf216dda4e6c3          0
2136   50  q0  bf5f2ac9b4454a79bd6848f10314bbee          0
2137   50  q0  e4adf192c95d4114a131174f6df262dd          1

[2138 rows x 4 columns]

In [25]:
assert (len(qrels_df)-len(qrels_readability_df))==len(issue_docs)

doc_issues = [x for x in list(qrels_df["docno"].unique()) if x not in list(qrels_readability_df["docno"].unique())]
print(len(doc_issues), len(set(issue_docs)))
for docno in doc_issues:
    print(docno, list(corpus.loc[corpus["docno"]==docno]["readability"])[0])

155 155
d82e5e4f531841d49bcd6fe7bd8cdf8f -1.0
44d7a109cd554b1cb44d2c3867ff7040 -1.0
0b9c61100ede42af9877beadb1efb5d7 -1.0
37d53c33110a4231807e71e377f08377 -1.0
59f02513ed164167acd899288008a031 -1.0
aa31a4d64bbf4accb37f37762307634f -1.0
1b85bcbd61624d669d6c0acac9ad4b98 -1.0
2e54ded87f644883a3584a0243c51e20 -1.0
86ab497754404406b7a1ed3c03ce9cfb -1.0
69153b48fc8a49d0b25288ff437c3710 -1.0
45b35de6fc3c4e18a022f3da33902aee -1.0
956d50deed2443debe6157dc6aa46915 -1.0
d40775523c5a4b2497f6489c872265c6 -1.0
48515a541041417f851fbd64fe9c9680 -1.0
8228edeaddca434d8f795450593fa982 -1.0
8180b99992b34e2ab0813e50222884ba -1.0
44cb123878434faea075424720f89016 -1.0
1b2c4fdbe9c64f029a41e061e7d8d984 -1.0
14383641f5b64feaa99c2749eb91e116 -1.0
d2b21431893a4ffaa6bb6f1881ccf08a -1.0
7b8dbd159ba44b0d99359bb901dd1211 -1.0
3c5bbc197c9d4f199a53f0da34d24bae -1.0
6346841f87a142c2a632784fd258cdea -1.0
fdfd2ff89afd4a62b5e3f9e2ce04f6f8 -1.0
be90e834297f4db88319ddcff9ee98e7 -1.0
edf2a26d48af4e10b9ccdfd9abba43a3 -1.0
07353522ca38432793312a5f8d597f6d -1.0
79dcf7fafa384770b219cbda8d515191 -1.0
e58f43efe1574f86be6131b4ed05aca4 -1.0
0ab8bde389d74b6387c6228ce08a494a -1.0
d0e64839e0804bc3a8455d527354238e -1.0
8cccf65c62d4458cb6934a2c678cf630 -1.0
2b73a066c03d449a85f47237ea7b8b29 -1.0
466d397cac4c4184837c358a97e93296 -1.0
8169e1fbc12644daa3661b554abfdd7e -1.0
c7bf126563264325b1f82ee49213855f -1.0
1c7dee99b3f94c29b31f0f9576b3c5ef -1.0
16e152ac8d084012a039e6fc840f27b6 -1.0
904f1a7f81bc4f0c9a5af76dcb97a8eb -1.0
38f9572c4a894934a1d250f0d29b7e0f -1.0
63d29774b5144d0eab385e69e9c563ae -1.0
7aba6942897447a7a745366500a7826b -1.0
6215ba451c7349a5a8056353a2969472 -1.0
6f8ca8247fce4c98b65ada0e1a4cfad0 -1.0
ab8433e4c9ad406abe0813f87890f2cb -1.0
769d19d6d2c1455cafff4dc39813af7c -1.0
f83d164c09d64af48f9a9974bf9dcaca -1.0
112a43d92cb84202a2f14efbc1b94d28 -1.0
e7f29eadce2342b4b4df213066d64988 -1.0
8b0ed7649afa4866bafc61874b539d27 -1.0
2691c0bcba834b73adf38051aae2fcbb -1.0
ef121d3b42e144f7939b4f64c3082a1f -1.0
16eef9c64dc748daa43c28669d9a24f6 -1.0
d9a7d6b24a0a437c8f656013b71ae5da -1.0
0e2a07d4cfc94eb29f44daed12876133 -1.0
6631c7692a2148beae63c0bdb6c82e70 -1.0
4edd9cd23f2541c1b412f101875c89f8 -1.0
2d0617efe1064cdcaf075c245ec9833d -1.0
d64e7914d50942419b3a19b88a283ac7 -1.0
8e57751570dc476f92596430b225a5b4 -1.0
910455d35240429bb7bee01008381749 -1.0
72f5b9a6978d479995c4d08ced764ac7 -1.0
7b6d5c4dd6e04e60852ee8604bdc114d -1.0
a4ffcc8175fa4bf5a1c26fcb8be453e1 -1.0
318b445892314cd4bee9a7ae52bb107d -1.0
96eec49ab5d54181a4232461bddc605f -1.0
6eda889acf604f0883e18839719783db -1.0
4d3d7a53d3e94c0e8436ad9336568725 -1.0
cb60c0cf621c479da9034f23bc3e534a -1.0
82bcbd53dc5c43a1bf68644210cc953d -1.0
59bb9aa5bd7d4e369019e84544ad6925 -1.0
6131fd16b2ac4d0fb9b2e9db70d79dd2 -1.0
4b3391b409a045c7b37026707dcd0a54 -1.0
d5460e0ebf1941edbeb89993cfef4583 -1.0
b3672b6411414f5fb9a39cde7c24ac0f -1.0
b2dd6267bc194f63b6056301ae8180eb -1.0
3c58e8ac7fa747d8a1d0c9efdf6a7986 -1.0
18916880aaae4346b935c7a9ad454331 -1.0
e5500a7645674de2922c1bd9756e5d4d -1.0
3962784e48c74098b7ab4b5ffe0a6333 -1.0
5aff36b447a7406eb9501a4d1e7ac84e -1.0
091c63faea0147218f7cba13e8a50b85 -1.0
2bfc7a9adc15467ca33e720af168f26f -1.0
aa68925ce88a47449dd183f25169dfab -1.0
50d89b15aff242d3bc1fdc129502b1b9 -1.0
75ea16a489654e5085a907cdc36f604c -1.0
7bdf3f8afbbc479d90ad4d888073fdec -1.0
86a0717cad714d8ca47852b0674c0028 -1.0
35b2a752f1a94179a56149edc6b7edb8 -1.0
434d22854a75419087365b6c615fe371 -1.0
76534d923c794ff6bb245688383d4ba9 -1.0
162c880249254e06b976f5b4d63c9601 -1.0
28c6430574454e09aff31f4658a9ce59 -1.0
7492ca6ad69c4e85a1b7237ef7af42db -1.0
08054eacddd0483baa9b69da00a01497 -1.0
021c5c2084ac4d57bde7186d37901d6d -1.0
dbfafccf3c004754acb87226efa109e3 -1.0
5e554981e03d4fbb9babc04ce3fcef37 -1.0
816304940db246d6be006c1507cc9b06 -1.0
ec56efe011dd467fb4b6cfcdf8a7619b -1.0
cccc6cbc8d4946c59a527fb60c4ab500 -1.0
c08a5130bd7a404bb91081c35e2a112d -1.0
f6bdde7c51aa4aa8a3457a728c7ff871 -1.0
c573e2778ac74ecd8d9be00790235fba -1.0
0d990fa14d1a47118204952aae9007e2 -1.0
450a2b26f691467abeac8f174ff41d0f -1.0
fc4faef4cd044989874905133d8cf55b -1.0
dccf8df6998c400b8a706469586787b8 -1.0
06180d11fdb844f28157d0814476ca2c -1.0
d0f3d5c0bd1a4555ab450f158a352332 -1.0
41d1445f151940639d0f7a17a8de03bf -1.0
814ef2b4feaa4d00b802b3523ee0585e -1.0
161338fc0d0c4385a973f9d861940566 -1.0
6659b8d0711144e8883ee31dee443dd2 -1.0
750396d8c2964a3d902c416fd56f054f -1.0
7251f499927d408996747ff6e80e9ed1 -1.0
ec1c985a21f24d079087acdadcd91049 -1.0
da177a6e90744d158eee15a775bcabd9 -1.0
dc0adf30cf6c466a8b7af30e926a297c -1.0
b0e3fd69adbe4c0ea7d81b7a8362fe67 -1.0
95aeda4f27da4cbda402ec8961ffe00e -1.0
02324cf29a7c4a0ca9afa77255e3f8e9 -1.0
1eaa0a92971d4fc4a6395863356d244a -1.0
be673d9109d5449bab7dcced7be5bcf7 -1.0
4dd1ead696874a958274b3fc0822f280 -1.0
a0d4443f813d49f3b5bb4733650652c3 -1.0
7d8990896c4840d9a27d90d4e0474a0f -1.0
ab66bf5a07d84c52a558466115cce919 -1.0
4544b16682624a029b5f0ddda339b550 -1.0
1d9ed000f28a4f2c94bf7c72f0204c33 -1.0
a442546344234166b6ddf11fa82cda4c -1.0
19f4141c080043c680ea604749532cc3 -1.0
71f6b7b3ad2d4f689eec93c8e3e998ea -1.0
02c82fe2db8746ac8e6789efac91e823 -1.0
5ea8923290e94f09a08e066f5f95660f -1.0
c92fca209161431c96a5529f6fab637e -1.0
8e71f0f4bffe46c3ba6ff783ccb663e8 -1.0
583295b60d5f4fb5846716aaf4bcb2b7 -1.0
df3b3fe404544c928a1df40b642a98c9 -1.0
0495b593564a41bebb1dc971070413e4 -1.0
2c147427b6de4e3f91d49de27acd42e5 -1.0
de97a08d98114112b33ed9e28c4acbb7 -1.0
a6801523cf40467797fe14329a4f2397 -1.0
c2a251b89e224009ac1765bf4dd1d395 -1.0
0b7268560a55488996abb9f7ad44c62c -1.0
9dd3012a423a41f4a3dc4f3521a5b1a5 -1.0
e04c90cf4abd41b4a6a129c7a0da43af -1.0
01c0ff1de9414afaa2319f436257aaa3 -1.0
db2c3a6083564168ba7e5ae615ecbd9d -1.0
8125ae155e0e4ea79e1859d3e3916279 -1.0
8efb8f3389384505ad6cee4096c8fea8 -1.0
c68cde8055474674806606a728d8f45e -1.0
abe5e1c44bcf4e13aac29a73033df812 -1.0
3e606883584d44e29dc248a25e71fe86 -1.0
c5ae52e73e074098ba049a1af466ec1b -1.0

In [26]:
# # graded readability labels (zuccon formula): same query-doc pairs as qrels-relevance-binary.csv

# from tqdm.notebook import tqdm
# import pandas as pd
# from utils import get_graded_readability_rel_zuccon

# # nltk.download('all', halt_on_error=False)
# corpus = pd.read_csv("../kid-friend-en/en/inputs/documents.csv")
# qrels_df = pd.read_csv("../kid-friend-en/en/qrels/qrels-relevance-binary.csv")
# qrels_readability = qrels_df
# read_relevance = []

# for _, row in tqdm(qrels_readability.iterrows(), total=len(qrels_readability)):
#     docid = row["docno"]
#     readability = list(corpus.loc[corpus["docno"]==docid]["readability"])[0]
#     read_relevance.append(readability)

# qrels_df["read_relevance"] = read_relevance
# qrels_df["read_relevance_label"] = get_graded_readability_rel_zuccon(qrels_df["read_relevance"], threshold=4)
# qrels_df.drop(["relevance", "read_relevance"], axis=1, inplace=True)
# qrels_df = qrels_df.rename({"read_relevance_label": "relevance"}, axis=1)
# qrels_df.to_csv("../kid-friend-en/en/qrels/qrels-readability-graded.csv", index=False)
# qrels_df

In [27]:
# qrels_df.loc[qrels_df["relevance"].isna()] # checking if any doc had invalid readability score

In [28]:
# qrels_df = qrels_df.dropna(subset=["relevance"]) # remove query-doc pairs where the doc had an invalid readability score
# qrels_df.to_csv("../kid-friend-en/en/qrels/qrels-readability-graded.csv", index=False)
# qrels_df

### Objectivity + Relevance

### Educational Alignment + Relevance